branch-defaults:
  master:
    environment: portfolio-prod
environment-defaults:
  Portfolio-env:
    branch: null
    repository: null
global:
  application_name: portfolio
  default_ec2_keyname: django_blog_keyPair
  default_platform: Python 3.13 running on 64bit Amazon Linux 2023
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
